server:
  port: 8082
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/goldenkids?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
logging:
  level:
    root: debug
app:
  uploadPath: /home/ubuntu/filestorage
  JWT_HEADER_A: "Authorization"
  JWT_HEADER_R: "Refresh"
  JWT_KEY : "d1f33e03-f067-4315-af91-b03f91f4cb19"
  JWT_PREFIX : "BEARER"
  JWT_REFRESH_EXPIRATION : "604800000"