spring:
  datasource:
    username: root
    password: root1423
    url: jdbc:mysql://localhost:3306/goldenkids?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
logging:
  level:
    root: info
servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 50MB
app:
  uploadPath: C:\\develop\\upload-files
