server:
  port: 8082
spring:
  datasource:
    username: root
    password: root1423
    url: jdbc:mysql://138.2.127.212:3306/goldenkids?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
logging:
  level:
    root: debug
app:
  uploadPath: /home/ubuntu/filestorage
